version: "3.9"
services:
  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
            default:
                connector: postgres
                host: ec2-52-21-153-207.compute-1.amazonaws.com
                port: "5432"
                database: daqthqeakm9tgv
                ssl: true
                user: grqmnwsjssbdpi
                password: 506ed2bfed27c2503570ff43dd89de7f4012a140ca3761ac8633454f1ed12f3
                migrations: true
