version: "3.9"
services:
    prisma:
        image: prismagraphql/prisma:1.34.10
        restart: always
        ports:
            - "4466:4466"
        environment:
            PRISMA_CONFIG: |
                port: 4466
                databases:
                    default:
                        connector: postgres
                        host: localhost
                        port: "5432"
                        database: graphql-prisma-course-1
                        ssl: true
                        schema: public
                        user: ajay
                        password: password
                        migrations: true
